export const FETCH_LISTS = 'FETCH_LISTS'
export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const ADD_COLUMN = 'ADD_COLUMN'
export const DELETE_COLUMN = 'DELETE_COLUMN'
export const LOADING_START = 'LOADING_START'
export const LOADING_STOP = 'LOADING_STOP'

export const HANDLE_EDIT = 'HANDLE_EDIT'
export const SEARCH = 'SEARCH'
export const CANCEL_EDIT = 'CANCEL_EDIT'
export const SET_COL_TITLE = 'SET_COL_TITLE'
